# Treesitter scopes
"attribute" = "magenta"
"type" = "rose"
"type.builtin" = "seafoam"
"type.parameter" = "altred"
"type.enum" = "rose"
"type.enum.variant" = "royal"
"constructor" = "royal"
"constant" = "royal"
"constant.builtin" = "seafoam"
"constant.builtin.boolean" = "cyan"
"constant.character" = "fg"
"constant.character.escape" = "white"
"constant.numeric" = "fg"
"string" = "light_red"
"string.special.path" = "light_orange"
"string.special.url" = "seafoam"
"comment" = "dark_gray"
"variable" = "red"
"variable.builtin" = "seafoam"
"variable.parameter" = "altred"
"variable.other.member" = "magenta"
"variable.other.member.private" = "royal"
"label" = "cyan"
"punctuation" = "brite"
"keyword" = "cyan"
"keyword.operator" = "fg"
"keyword.directive" = "royal"
"operator" = "fg"
"function" = "yellow"
"function.macro" = "orange"
"function.special" = "orange"
"tag" = "cyan"
"namespace" = "royal"
"special" = "seafoam"
"markup" = "fg"
"markup.heading" = "cyan"
"markup.list" = "seafoam"
"markup.bold" = "royal"
"markup.italic" = "dark_gray"
"markup.strikethrough" = "white"
"markup.link" = "seafoam"
"markup.quote" = "light_red"
"markup.raw" = "altred"
"diff" = "fg"
"diff.plus" = "sign_add"
"diff.minus" = "sign_delete"
"diff.delta" = "sign_change"
"type.macro.rust" = "orange"

# Interface
"ui.background" = {bg = "bg"}
"ui.cursor" = { modifiers = ["reversed"]}
"ui.cursor.match" = {fg="brite", bg="neongreen"}
"ui.debug.breakpoint" = "sign_delete"
"ui.debug.active" = "sign_change"
"ui.gutter" = "lightdark"
"ui.gutter.selected" = {fg= "fg", bg = "dark"}
"ui.linenr" = "darkred"
"ui.linenr.selected" = "red"
"ui.selection" = {bg="tree_gray"}
"ui.statusline" = {fg = "fg", bg = "dark"}
"ui.statusline.inactive" = "solar_orange"
"ui.statusline.normal" = "neon"
"ui.statusline.insert" = "error_red"
"ui.statusline.select" = "royal"
"ui.virtual.indent-guide" = "chunk"
"ui.picker.header" = "rose"
"ui.popup" = {fg="fg",bg="NONE"}
"ui.window" = {fg="fg",bg="NONE"}
"ui.menu" = {fg="fg",bg="NONE"}
"warning" = "sign_change"
"error" = "sign_delete"
"info" = "sign_add"
"hint" = "dark_gray"
"diagnostic.hint" = "dark_gray"
"diagnostic.info" = "sign_add"
"diagnostic.warning" = "sign_change"
"diagnostic.error" = "sign_delete"
"diagnostic.unnecessary" = "dark_gray"
"diagnostic.deprecated" = "solar_orange"

[palette]
fg               = "#ffb7f8"
bg               = "#0a0002"
alt_fg           = "#a69f55"
alt_bg           = "#0e060c"
cursor_fg        = "#db0000"
cursor_bg        = "#0a0000"
dark             = "#360808"
accent           = "#ee52c7"
black            = "#000000"
line             = "#46102a"
gray             = "#e0e9ff"
white            = "#f5f5f5"
brite            = "#ffffff"
bluwhite         = "#c8d3ff"
dark_gray        = "#9a81d9"
context          = "#de8cff"
light_gray       = "#efb2dd"
tree_gray        = "#1b1f27"
star_purple      = "#b8a9ff"
light_purple     = "#9586f4"
royal            = "#554cff"
purp             = "#5200cc"
magenta          = "#b94fff"
rose             = "#ff53ba"
light_red        = "#f85d75"
red              = "#e6041e"
altred           = "#c60091"
chunk            = '#f9003f'
darkred          = "#ad0023"
lightdark        = "#7f0800"
light_orange     = "#ff8b61"
orange           = "#ff5314"
solarorange      = "#cf4c00"
star_orange      = "#ffc867"
yellow           = "#f0ea0d"
bright_yellow    = "#f1ff0b"
star_yellow      = "#fff88a"
neon             = '#DFFF00'
star_green       = "#9CFFD3"
seafoam          = "#00e488"
neongreen        = '#00D700'
cyan             = "#07e4f6"
star_blue        = "#a9d8ff"
darkblue         = '#00005F'
sign_add         = "#157041"
sign_change      = "#c3ef1f"
sign_delete      = "#cb2a2a"
error_red        = "#e40000"
warning_orange   = "#ff670f"
info_yellow      = "#efdf00"
hint_blue        = "#17ffa3"
success_green    = "#14C50B"
ui2_blue         = "#042E48"
ui3_blue         = "#0195F7"
# from lualine
ll_black         = '#202020'
shellblue        = '#00DFFF'
darkgray         = '#3c3836'
lightgray        = '#504945'
inactivegray     = '#7c6f64'
uglyorange       = '#FFAF00'
barnred          = '#b32727'
brightorange     = '#C08A20'
brightred        = '#d22424'
anothercyan      = '#00DFFF'
noen             = '#ad0925'
# added            = { fg = '#00881b' }
# modified         = { fg = '#f42b4c' }
# removed          = { fg = '#d6071f' }
# error            = { fg = '#d6071f' }
# warn             = { fg = '#e7008b' }
# info             = { fg = '#5200cc' }
# hint             = { fg = '#00881b' }
